[package]
name = "hybrid-bar"
authors = [ "varsity <varsity@duck.com>" ]
version = "0.2.9"
edition = "2021"
description = "A simple status bar made for wlroots compositors."
license = "MIT"

[dependencies]
strum = { version = "0.24", features = ["derive"] }
tokio = { version = "1.21.2", features = ["full"] }
uuid = { version = "1.2.1", features = ["v4", "fast-rng"] }
gtk-layer-shell = "0.4.1"
lazy_static = "1.4.0"
strum_macros = "0.24"
glib = "0.15.12"
json = "0.12.4"
gtk = "0.15.5"

[profile.release]
opt-level = 3
panic = "abort"
strip = true
lto = "fat"
