[package]
name = "hybrid-bar"
authors = [ "varsity <varsity@duck.com>" ]
version = "0.3.9"
edition = "2021"
description = "A simple status bar made for wlroots compositors."
license = "MIT"

[dependencies]
strum = { version = "0.24.1", features = ["derive"] }
tokio = { version = "1.21.2", features = ["full"] }
gtk-layer-shell = "0.5.0"
strum_macros = "0.24.3"
lazy_static = "1.4.0"
heapless = "0.7.16"
glib = "0.16.2"
json = "0.12.4"
gtk = "0.16.0"

[profile.release]
panic = "abort"
opt-level = 3
strip = true
lto = "fat"
