[package]
name = "hybrid-bar"
authors = [ "varsity <varsity@duck.com>" ]
version = "0.3.9"
edition = "2021"
description = "A simple status bar made for wlroots compositors."
license = "MIT"

[dependencies]
strum = { version = "*", features = ["derive"] }
tokio = { version = "*", features = ["full"] }
gtk-layer-shell = "*"
strum_macros = "*"
lazy_static = "*"
heapless = "*"
glib = "*"
json = "*"
gtk = "*"

[profile.release]
panic = "abort"
opt-level = 3
strip = true
lto = "fat"
