[package]
name = "hybrid-bar"
authors = [ "varsity <varsity@duck.com>" ]
version = "0.2.2"
edition = "2021"
description = "A simple status bar made for wlroots compositors."
license = "MIT"

[dependencies]
strum = { version = "0.24", features = [ "derive" ] }
lazy_static = "1.4.0"
gtk-layer-shell = "0.4.1"
strum_macros = "0.24"
glib = "0.15.12"
json = "0.12.4"
gtk = "0.15.5"

# Optimizes for size
[profile.release]
opt-level = "z"
panic = "abort"
strip = true
lto = true
