[package]
name = "hybrid-bar"
description = "A simple status bar made for wlroots compositors."
authors = [ "varsity <refined@skiff.com>" ]
readme = "README.md"
repository = "https://github.com/vars1ty/HybridBar"
keywords = [ "gui", "wayland", "status-bar", "gtk-layer-shell", "linux" ]
categories = [ "rendering" ]
version = "0.4.7"
edition = "2021"
license = "MIT"

[dependencies]
tokio = { version = "*", features = [ "full" ] }
tracing-subscriber = "*"
gtk-layer-shell = "*"
strum_macros = "*"
lazy_static = "*"
lxinfo = "*"
stray = "*"
glib = "*"
json = "*"
gtk = "*"

[profile.release]
codegen-units = 1
panic = "abort"
opt-level = "z"
strip = true
lto = "fat"
