[package]
name = "hybrid-bar"
authors = [ "varsity <varsity@duck.com>" ]
version = "0.1.5"
edition = "2021"
description = "A simple status bar made for wl-roots."
license = "MIT"

[dependencies]
strum = { version = "0.24", features = [ "derive" ] }
gtk-layer-shell = "0.4.1"
strum_macros = "0.24"
cmd_lib = "1.3.0"
glib = "0.15.12"
json = "0.12.4"
gtk = "0.15.5"

# Optimizes for size
[profile.release]
opt-level = "z"
panic = "abort"
strip = true
lto = true
